<a href="https://colab.research.google.com/github/redrum88/tensorflow/blob/main/00_tensorflow_fundementals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. TensorFlow Fundamentals Exercises
1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [6]:
# Import tools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

# Check TensorFlow version
tf.__version__

'2.9.2'

## 1.Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [13]:
# Create a vector

vector = tf.constant([10, 8])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>

In [12]:
# Create a scalar
scalar = tf.constant(3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [16]:
# Create a matrix
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [17]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]],
                      [[10, 11, 12],
                       [13, 14, 15],
                       [16, 17, 18]]])

tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

## 2.Find the shape, rank and size of the tensors you created in 1.

In [23]:
print("Tensor shape:", tensor.shape)
print(f"Tensor rank: {tf.rank(tensor)}")
print(f"Tensor size: {tf.size(tensor)}")

Tensor shape: (2, 3, 3)
Tensor rank: 3
Tensor size: 18


## 3.Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [24]:
tf.random.set_seed(42)

# Create tensors
tensor_1 = tf.random.uniform(shape=(5, 300))
tensor_2 = tf.random.uniform(shape=(5, 300))

tensor_1, tensor_1.shape, tensor_2, tensor_2.shape

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 TensorShape([5, 300]),
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.828

## 4.Multiply the two tensors you created in 3 using matrix multiplication.

`tf.linalg.matmul`

Multiplies matrix `a` by matrix `b`, producing `a` * `b`

https://www.tensorflow.org/api_docs/python/tf/linalg/matmul

In [31]:
tf.matmul(tensor_1, tf.transpose(tensor_2)) #  Transposes last two dimensions of tensor `tensor_2`.

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

In [38]:
print("Before matrix multiplication:")
print(f"Tensor 1 shape {tensor_1.shape} vs. {tensor_2.shape} Tensor 2 shape\n")
result = tf.linalg.matmul(tensor_1 , tf.transpose(tensor_2))
print(f"Result after multiplying:\n {result} \n")
print(f"Shape after multiplying: {result.shape}")

Before matrix multiplication:
Tensor 1 shape (5, 300) vs. (5, 300) Tensor 2 shape

Result after multiplying:
 [[80.33345  73.40498  77.159615 73.98369  80.90053 ]
 [75.146355 68.80437  74.24302  71.841835 75.60206 ]
 [79.7594   75.644554 77.797585 74.74873  80.559845]
 [75.08526  69.064064 74.30776  72.27616  76.05669 ]
 [85.05688  74.26627  78.00687  74.88679  83.13417 ]] 

Shape after multiplying: (5, 5)


## 5.Multiply the two tensors you created in 3 using dot product.

In [39]:
tf.tensordot(tensor_1, tf.transpose(tensor_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40498 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.60206 ],
       [79.7594  , 75.644554, 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00687 , 74.88679 , 83.13417 ]],
      dtype=float32)>

## 6.Create a tensor with random values between `0` and `1` with shape `[224, 224, 3]`.

In [40]:
tensor_3 = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
tensor_3.shape

TensorShape([224, 224, 3])

In [41]:
tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

## 7.Find the min and max values of the tensor you created in 6 along the first axis.

In [43]:
# Print min and max value of tensor.
print(f"Min value: {tf.reduce_min(tensor_3)}\n")
print(f"Max value: {tf.reduce_max(tensor_3)}")


Min value: 2.384185791015625e-07

Max value: 0.999991774559021


## 8.Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [51]:
# Create a tensor

before_squeeze = tf.random.Generator.from_seed(42)

before_squeeze = before_squeeze.normal(shape=(1, 224, 224, 3))

before_squeeze.shape

TensorShape([1, 224, 224, 3])

In [52]:
# Squeeze a tensor

after_squeeze = tf.squeeze(before_squeeze)

after_squeeze.shape

TensorShape([224, 224, 3])

## 9.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [53]:
tensor_5 = tf.constant([1, 3, 5, 5.5, 7, -10, -1.054, 0, 1.2461, 0.12422])
tensor_5

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([  1.     ,   3.     ,   5.     ,   5.5    ,   7.     , -10.     ,
        -1.054  ,   0.     ,   1.2461 ,   0.12422], dtype=float32)>

In [57]:
max_value = tf.math.argmax(tensor_5)
print(f"The indices where the value is maximum:: {max_value}")
print(f'The maximum value was: {tensor_5[max_value]}')

The indices where the value is maximum:: 4
The maximum value was: 7.0


## 10.One-hot encode the tensor you created in 9.

In [59]:
tf.one_hot(tensor_5, depth=10)

InvalidArgumentError: ignored

InvalidArgumentError: Value for attr 'TI' of float is not in the list of allowed values: uint8, int32, int64

In [60]:
tensor_5.dtype

tf.float32

`tf.cast` https://docs.w3cub.com/tensorflow~python/tf/cast

In [61]:
tf.cast(tensor_5, dtype=tf.int32)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([  1,   3,   5,   5,   7, -10,  -1,   0,   1,   0], dtype=int32)>

In [62]:
tf.one_hot(tf.cast(tensor_5, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>